version: '3.4'

services:

  web:
    environment:
    - "ASPNETCORE_ENVIRONMENT=Development"

  api:
    environment:
    - "ASPNETCORE_ENVIRONMENT=Development"

  sql:
    build:
      context: sql/.
    # for debugging
    # entrypoint: ["sh", "-c", "sleep infinity"]
    restart: always
    labels:
    - "traefik.enable=false"

  store:
    environment:
    - "SQL_CONNECTION_STRING=Server=sql;Database=ContainerVote;User Id=sa;Password=4DevTestOnly"

  calculate:
    environment:
    - "SQL_CONNECTION_STRING=Server=sql;Database=ContainerVote;User Id=sa;Password=4DevTestOnly"
