FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy shared libraries
COPY ContainerVote.Shared.Primitives/. ContainerVote.Shared.Primitives/.

# copy csproj and restore as distinct layers
WORKDIR ContainerVote.Calculate
COPY ContainerVote.Calculate/*.csproj .
RUN dotnet restore

# copy everything else and build app
COPY ContainerVote.Calculate/. .
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime AS runtime
WORKDIR /app
COPY --from=build /app/ContainerVote.Calculate/out .
ENTRYPOINT ["dotnet", "ContainerVote.Calculate.dll"]