version: '3.4'

services:

  traefik:
    volumes:
    - ${WEBAPP_STORAGE_HOME}/traefik:/etc/traefik

  containervote.web:
    build: ""
    labels: []

  containervote.api:
    build: ""
    labels: []

  redis:
    labels: []

  containervote.store:
    build: ""

  containervote.calculate:
    build: ""