FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy shared libraries
COPY ContainerVote.Shared.Primitives/. ContainerVote.Shared.Primitives/.

# copy csproj and restore as distinct layers
WORKDIR ContainerVote.Api
COPY ContainerVote.Api/*.csproj .
RUN dotnet restore

# copy everything else and build app
COPY ContainerVote.Api/. .
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/ContainerVote.Api/out .
ENTRYPOINT ["dotnet", "ContainerVote.Api.dll"]