version: '3'

services:

  traefik:
    image: traefik
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    - ${WEBAPP_STORAGE_HOME}/traefik:/etc/traefik
    restart: always
    
  web:
    image: "bgever/container-vote:web-latest"
    ports:
    - "80"
    restart: always
  
  api:
    image: "bgever/container-vote:api-latest"
    ports:
    - "80"
    restart: always
    
  redis:
    image: "redis:alpine"
    restart: always