FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy shared libraries
COPY ContainerVote.Shared.Primitives/. ContainerVote.Shared.Primitives/.

# copy csproj and restore as distinct layers
WORKDIR ContainerVote.Store
COPY ContainerVote.Store/*.csproj .
RUN dotnet restore

# copy everything else and build app
COPY ContainerVote.Store/. .
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime AS runtime
WORKDIR /app
COPY --from=build /app/ContainerVote.Store/out .
ENTRYPOINT ["dotnet", "ContainerVote.Store.dll"]