kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: container-vote
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    name: web
  - protocol: TCP
    port: 8080
    name: admin